#! /bin/sh
NODE_ENV=production
DAEMON="npm start"
NAME=PlayTask
DESC=PlayTask
PIDFILE="playtask.pid"
case "$1" in
start)
	echo "Starting $DESC: "
	nohup $DAEMON > /dev/null &
	echo $! > $PIDFILE
	echo "$NAME."
	;;
stop)
	echo "Stopping $DESC: "
	pid='cat $PIDFILE'
	kill $pid
	rm $PIDFILE
	echo "$NAME."
	;;
esac
exit 0